name: test-file

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  my-test:
    runs-on: ubuntu-latest

    steps:
      - name: print working directory
        run: pwd

      - name: llist all files
        run: ls -a
      

      - name: Checkout
        uses: actions/checkout@v6.0.1
