name: test-file

on:
  push:
    branches: 
      - main
  

jobs:

  my-test:
    runs-on: ubuntu-latest

    steps:
      - name: print working directory
        run: pwd

      - name: date
        run: date
